USE conference;

CREATE TABLE ticket
(
    id BINARY(16) NOT NULL PRIMARY KEY,
    type ENUM('COMPLETE_ONLINE_EXPERIENCE', 'COMPLETE_ON_SITE_EXPERIENCE', 'ONLINE_EXPERIENCE', 'ON_SITE_EXPERIENCE'),
    price ENUM('200', '250', '300', '350')
);